eureka:
    instance:
        hostname: localhost
    client:
        serverUrl:
            defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
spring:
  cloud:
    config:
      override-system-properties: false

management:
  zipkin:
    base-url: http://localhost:9411
  tracing:
    sampler:
      probability: 1