spring:
  application:
    name: customer-service
  data:
    mongodb:
      host: localhost
      port: 27017
      username: root
      password: root
      database: customer
      authentication-database: admin

server:
  port: 0