spring:
  application:
    name: customer-service
  data:
    mongodb:
      uri: mongodb://customer-db-mongodb:27017/customer_db # Kubernetes DNS
      username: customer_user
      password: customer_pass
      authentication-database: admin

server:
  port: 8090
