apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-service-pod
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: multi-service-pod
  template:
    metadata:
      labels:
        app: multi-service-pod
    spec:
      initContainers:
        - name: config-server
          image: {{ .Values.containers.config_server.image }}
          ports:
            - containerPort: {{ .Values.containers.config_server.port }}

      containers:
        - name: gateway
          image: {{ .Values.containers.gateway.image }}
          ports:
            - containerPort: {{ .Values.containers.gateway.port }}

        - name: customer-service
          image: {{ .Values.containers.customer_service.image }}
          ports:
            - containerPort: {{ .Values.containers.customer_service.port }}

        - name: product-service
          image: {{ .Values.containers.product_service.image }}

        - name: order-service
          image: {{ .Values.containers.order_service.image }}

        - name: payment-service
          image: {{ .Values.containers.payment_service.image }}

        - name: notification-service
          image: {{ .Values.containers.notification_service.image }}

        - name: discovery-service
          image: {{ .Values.containers.discovery_service.image }}
          ports:
            - containerPort: {{ .Values.containers.discovery_service.port }}

        
