apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-service-pod
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: multi-service-pod
  template:
    metadata:
      labels:
        app: multi-service-pod
    spec:
      initContainers:
        - name: wait-for-config-server
          image: busybox # Lightweight image to check readiness
          command:
            [
              "sh",
              "-c",
              "until nc -z config_server 8888; do echo waiting for config server; sleep 5; done;",
            ]

      containers:
        - name: gateway
          image: {{ .Values.containers.gateway.image }}
          ports:
            - containerPort: {{ .Values.containers.gateway.port }}

        - name: customer_service
          image: {{ .Values.containers.customer_service.image }}
          ports:
            - containerPort: {{ .Values.containers.customer_service.port }}

        - name: product_service
          image: {{ .Values.containers.product_service.image }}

        - name: order_service
          image: {{ .Values.containers.order_service.image }}

        - name: payment_service
          image: {{ .Values.containers.payment_service.image }}

        - name: notification_service
          image: {{ .Values.containers.notification_service.image }}

        - name: discovery_service
          image: {{ .Values.containers.discovery_service.image }}
          ports:
            - containerPort: {{ .Values.containers.discovery_service.port }}

        - name: config_server
          image: {{ .Values.containers.config_server.image }}
          ports:
            - containerPort: {{ .Values.containers.config_server.port }}
