apiVersion: v1
kind: Service
metadata:
  name: ecommerce-service
spec:
  selector:
    app: multi-service-pod # Make sure this matches the label in your pod template
  ports:
    - protocol: TCP
      port: 80 # Exposed port for the service
      targetPort: 8222 # Target port in the container (gateway service in this case)
  type: LoadBalancer # Expose the service outside the cluster