apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  type: LoadBalancer # or ClusterIP if using Ingress
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 80 # Exposed Port
      targetPort: 8222 # Gateway Port
