server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/phu-phurithat/springboot-ecommerce-config.git
          default-label: master
          clone-on-start: true
