replicaCount: 1

initContainers:
  - name: wait-for-config-server
    image: busybox
    command:
      - "sh"
      - "-c"
      - "until nc -z config-server 8888; do echo waiting for config server; sleep 5; done;"

containers:
  gateway:
    image: phuphurithat/ecommerce:gateway
    port: 8222

  customer_service:
    image: phuphurithat/ecommerce:customer-service
    port: 8090

  product_service:
    image: phuphurithat/ecommerce:product-service

  order_service:
    image: phuphurithat/ecommerce:order-service

  payment_service:
    image: phuphurithat/ecommerce:payment-service

  notification_service:
    image: phuphurithat/ecommerce:notification-service

  discovery_service:
    image: phuphurithat/ecommerce:discovery-service
    port: 8761

databases:
  mysql:
    enabled: true
    product:
      enabled: true
      rootPassword: root
      database: product_db
      user: product_user
      password: product_pass
    payment:
      enabled: true
      rootPassword: root
      database: payment_db
      user: payment_user
      password: payment_pass
    order:
      enabled: true
      rootPassword: root
      database: order_db
      user: order_user
      password: order_pass

  mongodb:
    enabled: true # Set to true to enable MongoDB databases
    customer:
      enabled: true
      rootPassword: root
      database: customer_db
      user: customer_user
      password: customer_pass
    notification:
      enabled: true
      rootPassword: root
      database: notification_db
      user: notification_user
      password: notification_pass

messaging:
  kafka:
    enabled: true

tracing:
  zipkin:
    enabled: true
