replicaCount: 1

initContainers:
  - name: wait-for-config-server
    image: busybox
    command:
      - "sh"
      - "-c"
      - "until nc -z config-server 8888; do echo waiting for config server; sleep 5; done;"

containers:
  gateway:
    image: phuphurithat/ecommerce:gateway
    port: 8222

  customer_service:
    image: phuphurithat/ecommerce:customer-service
    port: 8090

  product_service:
    image: phuphurithat/ecommerce:product-service

  order_service:
    image: phuphurithat/ecommerce:order-service

  payment_service:
    image: phuphurithat/ecommerce:payment-service

  notification_service:
    image: phuphurithat/ecommerce:notification-service

  discovery_service:
    image: phuphurithat/ecommerce:discovery-service
    port: 8761

  config_server:
    image: phuphurithat/ecommerce:config-server
    port: 8888

databases:
  customer:
    enabled: true
    mongodb:
      auth:
        username: customer_user
        password: customer_pass
        database: customer_db

messaging:
  kafka:
    enabled: true

tracing:
  zipkin:
    enabled: true
