replicaCount: 1

initContainers:
  - name: wait-for-config-server
    image: busybox
    command:
      - "sh"
      - "-c"
      - "until nc -z config-server 8888; do echo waiting for config server; sleep 5; done;"

containers:
  gateway:
    image: phuphurithat/ecommerce:gateway
    port: 8222

  customer-service:
    image: phuphurithat/ecommerce:customer_service
    port: 8090

  product-service:
    image: phuphurithat/ecommerce:product_service

  order-service:
    image: phuphurithat/ecommerce:order_service

  payment-service:
    image: phuphurithat/ecommerce:payment_service

  notification-service:
    image: phuphurithat/ecommerce:notification_service

  discovery-service:
    image: phuphurithat/ecommerce:discovery_service
    port: 8761

  config-server:
    image: phuphurithat/ecommerce:config_server
    port: 8888

databases:
  customer:
    enabled: true
    mongodb:
      auth:
        username: customer_user
        password: customer_pass
        database: customer_db

messaging:
  kafka:
    enabled: true

tracing:
  zipkin:
    enabled: true
