apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-servivce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-servivce
  template:
    metadata:
      labels:
        app: customer-servivce
    spec:
      containers:
        - name: customer-servivce
          image: "phuphurithat/ecommerce:customer-service"
