name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - config-server
          - customer-service
          - order-service
          - payment-service
          - product-service
          - notification-service
          - gateway
          - discovery-service

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build ${{ matrix.service }} microservice
        run: mvn clean install -f services/${{ matrix.service }}/pom.xml

      - name: Build Docker image for ${{ matrix.service }}
        run: docker build -t phuphurithat/ecommerce:${{ matrix.service }} ./services/${{ matrix.service }}

      - name: Push Docker ${{ matrix.service }} image to registry
        run: docker push phuphurithat/ecommerce:${{ matrix.service }}
