name: CI Pipeline for Microservices

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.changed-services.outputs.matrix }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Detect Changed Services
        id: changed-services
        run: |
          echo "Detecting changes..."
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})

          SERVICES=""
          for service in product-service order-service payment-service; do
            if echo "$CHANGED_FILES" | grep -q "^$service/"; then
              SERVICES="$SERVICES \"$service\","
            fi
          done

          SERVICES="[${SERVICES%?}]"  # Remove last comma
          echo "Detected changed services: $SERVICES"
          echo "matrix=$SERVICES" >> $GITHUB_ENV
          echo "::set-output name=matrix::$SERVICES"

  build:
    runs-on: ubuntu-latest
    needs: detect-changes
    strategy:
      matrix:
        service: ${{ fromJson(needs.detect-changes.outputs.services) }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Service (${{ matrix.service }})
        run: mvn clean package -DskipTests
        working-directory: ${{ matrix.service }}

  test:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        service: ${{ fromJson(needs.detect-changes.outputs.services) }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run Tests for ${{ matrix.service }}
        run: mvn test
        working-directory: ${{ matrix.service }}
